products = [
	"cookies"
]

reactants = [
	"cookie_dough"
]

ingredients = """
5 c. cookie dough
"""

directions = """
1. Spoon balls of cookie dough onto a cookie sheet.
2. Bake at 375F for 10 to 14 minutes, until firm and brown.
"""

# How long does it take to cook?
time = "15m"