[[recipe]]
name = "grilled cheese sandwich"

products = [
	"grilled cheese sandwich"
]
time = "20m"
directions = """
Heat 1 tablespoon salted butter in a cast-iron or nonstick skillet over medium-low heat. 
Press the sandwich slightly and place it in the skillet. 
Cook until golden on the bottom, 3 to 5 minutes. 
Flip, adding more butter to the pan if needed, and 
cook until the other side is golden and the cheese melts, 3 to 5 more minutes.
"""

	[[recipe.ingredient]]
		name="cheese sandwich"
		measure = "whole"
		number = 1

	[[recipe.ingredient]]
		name="butter"
		measure = "tbl"
		number = 1

[[recipe]]
name = "cheese sandwich"

products = [
	"cheese sandwich"
]
time = "3m"
directions = """
Put the slices of cheese between the bread.
"""

	[[recipe.ingredient]]
		name="bread"
		measure = "slice"
		number = 2

	[[recipe.ingredient]]
		name="cheese"
		measure = "slice"
		number = 1


